// Generated by CoffeeScript 1.3.3
(function() {
  var last_truth_telling, paulistine_plugin;

  last_truth_telling = null;

  paulistine_plugin = (function() {

    function paulistine_plugin(plg_ldr, options, db) {
      this.db = db;
    }

    paulistine_plugin.prototype.name = 'paulistine';

    paulistine_plugin.prototype.msg_type = 'message';

    paulistine_plugin.prototype.version = '1';

    paulistine_plugin.prototype.commands = ['paulistine'];

    paulistine_plugin.prototype.match_regex = function() {
      return null;
    };

    paulistine_plugin.prototype.process = function(client, msg) {
      var an_hour_ago, part_five, part_four, part_one, part_three, part_two, timer_delay;
      an_hour_ago = Date.create('1 hour ago');
      if (last_truth_telling === null || an_hour_ago > last_truth_telling) {
        last_truth_telling = new Date();
        timer_delay = 3000;
        part_one = function() {
          client.say(msg.reply, "The year is 2031.");
          return setTimeout(part_two, timer_delay);
        };
        part_two = function() {
          client.say(msg.reply, "You've managed to escape from the FEMA camp you were forced into after a false flag dirty bomb attack was used to enact nation wide martial law.");
          return setTimeout(part_three, timer_delay);
        };
        part_three = function() {
          client.say(msg.reply, "As you run desperately toward the horizon you choke on the air full of aluminum oxide. Routine chem trailing ensures that only Monsanto's genetically modified creations grow, preventing criminal dissidents from growing their own food supply.");
          return setTimeout(part_four, timer_delay);
        };
        part_four = function() {
          client.say(msg.reply, "As you reach the top of a small hill you come face to face with the military's latest patrol-bot. In a fraction of a second the machine's sophisticated camera and computer system analyze your face and scan the biometric data in your subdermal implant. Immediately the drone opens fire, cutting you down in a hail of bullets that were manufactured in China.");
          return setTimeout(part_five, timer_delay);
        };
        part_five = function() {
          return client.say(msg.reply, "As you sputter out your final breath your one final thought is, \"If only I had voted for Ron Paul…\"");
        };
        return part_one();
      } else {
        return client.say(msg.reply, "Sorry, Dr. Paul says too much TRUTH can be " + "dangerous to the health of the uninitiated.");
      }
    };

    return paulistine_plugin;

  })();

  module.exports = {
    plugins: [paulistine_plugin]
  };

}).call(this);
