// Generated by CoffeeScript 1.3.3
(function() {
  var scrape, ud_plugin;

  scrape = require('../scrape');

  ud_plugin = (function() {

    function ud_plugin(plg_ldr, options, db) {
      this.options = options;
      this.db = db;
    }

    ud_plugin.prototype.name = 'ud';

    ud_plugin.prototype.msg_type = 'message';

    ud_plugin.prototype.version = '1';

    ud_plugin.prototype.commands = ['ud'];

    ud_plugin.prototype.match_regex = function() {
      return null;
    };

    ud_plugin.prototype.process = function(client, msg) {
      var raw_term, term, ud_search_url;
      raw_term = msg.msg.compact();
      term = raw_term.replace(" ", "+");
      if (term === '') {
        return client.say(msg.reply, "I need something to look up, dude.");
      } else {
        ud_search_url = "http://www.urbandictionary.com/define.php?term=" + term;
        return scrape.single(ud_search_url, function(body, window) {
          var $, stuff;
          $ = require('jquery').create(window);
          console.log("checking if exists");
          if ($('.definition').length === 0) {
            console.log("no matching ud term found");
            client.say(msg.reply, "Sorry, '" + raw_term + "' isn't defined yet.");
            return null;
          }
          stuff = $($('.definition')[0]).text().replace('\r', '. ').truncate(400);
          console.log("match found, about to say: " + stuff);
          return client.say(msg.reply, "\"" + stuff + "\"");
        });
      }
    };

    return ud_plugin;

  })();

  module.exports = {
    plugins: [ud_plugin]
  };

}).call(this);
