// Generated by CoffeeScript 1.3.3
(function() {
  var jsdom, scrape, wikipedia_plugin;

  jsdom = require('jsdom').jsdom;

  scrape = require('../scrape');

  wikipedia_plugin = (function() {

    function wikipedia_plugin(plg_ldr, options) {}

    wikipedia_plugin.prototype.name = 'wikipedia';

    wikipedia_plugin.prototype.msg_type = 'message';

    wikipedia_plugin.prototype.version = '1';

    wikipedia_plugin.prototype.commands = ['wiki'];

    wikipedia_plugin.prototype.match_regex = function() {
      return null;
    };

    wikipedia_plugin.prototype.process = function(client, msg) {
      var page, url;
      page = msg.msg.replace(' ', '%20');
      url = "http://en.wikipedia.org/w/api.php?format=json&action=parse" + ("&prop=text&page=" + page + "&redirects");
      return scrape.single(url, function(body) {
        var $, first_graf, wiki, wiki_body, window;
        wiki = JSON.parse(body);
        if (wiki.error != null) {
          return client.say(msg.reply, "Error doing wikipedia search: " + wiki.error.info);
        } else {
          wiki_body = "<html>\n<head><title>wiki</title></head>\n<body><div>" + wiki.parse.text['*'] + "</div></body>\n</html>";
          window = jsdom(wiki_body).createWindow();
          $ = require('jquery').create(window);
          first_graf = $('p:first').text();
          if (first_graf != null) {
            return client.say(msg.reply, "\"" + (first_graf.truncate(400)) + "\"");
          } else {
            return client.say(msg.reply, "no data found. hm.");
          }
        }
      });
    };

    return wikipedia_plugin;

  })();

  module.exports = {
    plugins: [wikipedia_plugin]
  };

}).call(this);
